### ISSUE TITLE
Incompatibility with ESP8266Audio-master ?

### ISSUE THREAD

**Issue by dagnall53** [earlephilhower/libmad-8266#1]
Earle, There is a (German) guy trying to programme an esp with my ESPRocnetsound code and he is getting a whole load of error messages when he compiles. They seem to be related to AudiogeneratorFLAC, which I do not (knowingly) use. 
He has listed the errors for me  on  https://www.thingiverse.com/thing:2689057/#comments (I have not copied all of it as it then loses some of the nice formatting..).
I think the key is he has both libmad-8266-master and ESP8266Audio-master installed.. do these play "nicely", or is this a possible cause of the issue..?

Thanks 
Dagnall

Example errors...
 `In file included from C:\Users\SWAT8989 Predator\Documents\Arduino\libraries\ESP8266Audio-master\src/AudioGeneratorFLAC.h:24:0,

             from C:\Users\SWAT8989 Predator\Documents\Arduino\libraries\ESP8266Audio-master\src\AudioGeneratorFLAC.cpp:21:`

 `Several libraries were found for "AudioFileSourceSPIFFS.h"
Used: C: \ Users \ SWAT8989 Predator \ Documents \ Arduino \ libraries \ libmad-8266-master 
Unused: C: \ Users \ SWAT8989 Predator \ Documents \ Arduino \ libraries \ ESP8266Audio-master `

**Comment by dagnall53** [comment]
UPDATE: 
I asked the guy to try removing libmad, and he did, and the code compiled..
Not sure how many people might have both audio libraries  installed, but if you get "issues", this might be a place to look!

**Comment by earlephilhower** [comment]
Actually, everyone who compiles using ESP8266Audio has both libmad and libflac, they're part of the actual repo as subdirs,

As for this repo, I would not recommend using it.  It was the one I used to do my changes to the lib code to allow it to build and run on the 8266, but there were several bugs found later and fixed in the main ESP8266Audio repo but not ported here.  I should really archive or delete this one...

**Comment by dagnall53** [comment]
Thanks,!
